FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_IAM_BASE_URL
ARG NEXT_PUBLIC_CMS_BASE_URL
ARG NEXT_PUBLIC_AGGREGATION_BASE_URL
ARG NEXT_PUBLIC_AUTH_MODE
ENV NEXT_PUBLIC_IAM_BASE_URL=$NEXT_PUBLIC_IAM_BASE_URL
ENV NEXT_PUBLIC_CMS_BASE_URL=$NEXT_PUBLIC_CMS_BASE_URL
ENV NEXT_PUBLIC_AGGREGATION_BASE_URL=$NEXT_PUBLIC_AGGREGATION_BASE_URL
ENV NEXT_PUBLIC_AUTH_MODE=$NEXT_PUBLIC_AUTH_MODE

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
