'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Locale = 'en' | 'ar';

export type WorkspaceThread = { id: string; title: string; locale: Locale };
export type WorkspaceInbox = { items?: Array<{ id: string; state: string; locale: Locale }>; unread_count?: number };
export type WorkspaceControls = { controls?: { read_enabled: boolean; llm_enabled: boolean; execution_enabled: boolean; schedules_enabled: boolean }; spend?: { interactive: boolean } };

export function OperatorThreadsPanel({ locale, threads, activeThreadID, onSelect, onToggleLocale, onDelete, onCreate }: { locale: Locale; threads: WorkspaceThread[]; activeThreadID?: string; onSelect: (thread: WorkspaceThread) => void; onToggleLocale: (thread: WorkspaceThread) => void; onDelete: (id: string) => void; onCreate: () => void }) {
  const ar = locale === 'ar';
  return <Card data-operator-panel="threads"><CardHeader><CardTitle className="text-base">{ar ? 'المحادثات' : 'Threads'}</CardTitle><p className="text-xs text-muted-foreground">{ar ? 'لغة كل محادثة محفوظة في CMS.' : 'Each thread’s locale is stored by CMS.'}</p></CardHeader><CardContent className="space-y-2">{threads.length ? threads.slice(0, 8).map((thread) => <div key={thread.id} className={`rounded-lg border p-2 text-xs ${activeThreadID === thread.id ? 'border-sky-500 bg-sky-50' : ''}`}><button className="w-full text-left" onClick={() => onSelect(thread)}><span className="block truncate font-medium">{thread.title}</span><span className="mt-1 block text-muted-foreground">{thread.locale === 'ar' ? 'العربية' : 'EN'} · <bdi className="font-mono">{thread.id.slice(0, 8)}</bdi></span></button><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => onToggleLocale(thread)}>{thread.locale === 'ar' ? 'EN' : 'ع'}</Button><Button size="sm" variant="outline" onClick={() => onDelete(thread.id)}>{ar ? 'حذف' : 'Delete'}</Button></div></div>) : <p className="text-xs text-muted-foreground">{ar ? 'لا توجد محادثات بعد.' : 'No threads yet.'}</p>}<Button variant="outline" size="sm" className="w-full" onClick={onCreate}>{ar ? 'محادثة جديدة' : 'New thread'}</Button></CardContent></Card>;
}

export function OperatorInboxPanel({ locale, inbox, lifecycleLabel, onOpen, onRefresh }: { locale: Locale; inbox: WorkspaceInbox; lifecycleLabel: (state: string) => string; onOpen: (id: string) => void; onRefresh: () => void }) {
  const ar = locale === 'ar';
  return <Card data-operator-panel="inbox"><CardHeader><CardTitle className="text-base">{ar ? 'صندوق المهام' : 'Task inbox'}</CardTitle><p className="text-xs text-muted-foreground">{ar ? `سجل مرتبط بالمنشئ · ${inbox.unread_count ?? 0} غير مقروء` : `Creator-bound history · ${inbox.unread_count ?? 0} unread`}</p></CardHeader><CardContent className="space-y-2">{inbox.items?.length ? inbox.items.map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className="w-full rounded-lg border p-3 text-left text-xs transition-colors hover:bg-muted"><div className="flex justify-between gap-2"><span className="font-medium">{lifecycleLabel(item.state)}</span><span>{item.locale === 'ar' ? 'العربية' : 'EN'}</span></div><div className="mt-1 truncate font-mono text-[10px] text-muted-foreground" dir="ltr">{item.id}</div></button>) : <p className="text-xs text-muted-foreground">{ar ? 'لا توجد تحقيقات دائمة بعد.' : 'No durable investigations yet.'}</p>}<Button variant="outline" size="sm" className="w-full" onClick={onRefresh}>{ar ? 'تحديث الصندوق' : 'Refresh inbox'}</Button></CardContent></Card>;
}

export function OperatorGovernancePanel({ locale, controls, loading, controlLabel, onRefresh }: { locale: Locale; controls?: WorkspaceControls; loading: boolean; controlLabel: (key: string) => string; onRefresh: () => void }) {
  const ar = locale === 'ar';
  return <Card data-operator-panel="governance"><CardHeader><CardTitle className="text-base">{ar ? 'الحوكمة' : 'Governance'}</CardTitle><p className="text-xs text-muted-foreground">{ar ? 'لا تمنع مفاتيح الإيقاف التحقق أو الإلغاء أو التسوية النهائية.' : 'Independent stops never block verification, cancellation, or terminalization.'}</p></CardHeader><CardContent className="space-y-2 text-xs">{controls ? <><div className="grid grid-cols-2 gap-2">{Object.entries(controls.controls ?? {}).filter((entry): entry is [string, boolean] => typeof entry[1] === 'boolean').map(([key, enabled]) => <div key={key} className="rounded border p-2"><span className="block text-muted-foreground">{controlLabel(key)}</span><span className={enabled ? 'text-emerald-700' : 'text-amber-700'}>{enabled ? (ar ? 'مفعّل' : 'enabled') : (ar ? 'معطّل' : 'disabled')}</span></div>)}</div><p className={controls.spend?.interactive ? 'text-amber-700' : 'text-muted-foreground'}>{controls.spend?.interactive ? (ar ? 'تحذير الإنفاق التفاعلي مفعّل.' : 'Interactive soft-spend warning is active.') : (ar ? 'تحذير الإنفاق التفاعلي واضح.' : 'Interactive soft-spend warning is clear.')}</p></> : <p className="text-muted-foreground">{loading ? (ar ? 'جارٍ تحميل عناصر التحكم…' : 'Loading governance controls…') : (ar ? 'عناصر التحكم غير متاحة.' : 'Governance controls unavailable.')}</p>}<Button variant="outline" size="sm" className="w-full" onClick={onRefresh}>{ar ? 'تحديث الحوكمة' : 'Refresh governance'}</Button></CardContent></Card>;
}
