'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, Pause, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { useAckOpsAttention, useMarkOpsBriefingSeen, useOpsAttention, useOpsBriefing, useOpsCommands, useOpsStatus, usePauseOpsFleet, usePauseOpsMember, useResumeOpsCommand, useSnoozeOpsAttention } from '@/hooks/use-operations-command-center';

const relative = (value?: string | null) => value ? new Intl.RelativeTimeFormat('en').format(Math.round((new Date(value).getTime() - Date.now()) / 60_000), 'minute') : 'never';
const tone = (value: string) => value === 'incident' || value === 'critical' || value === 'errored' || value === 'stalled' ? 'destructive' as const : value === 'attention' || value === 'major' || value === 'paused' ? 'warning' as const : value === 'all_clear' || value === 'idle' ? 'success' as const : 'secondary' as const;

export default function OperationsPage() {
    const status = useOpsStatus(); const attention = useOpsAttention(); const briefing = useOpsBriefing(); const commands = useOpsCommands();
    const ack = useAckOpsAttention(); const snooze = useSnoozeOpsAttention(); const pause = usePauseOpsFleet(); const pauseMember = usePauseOpsMember(); const resume = useResumeOpsCommand(); const seen = useMarkOpsBriefingSeen();
    const [reason, setReason] = useState(''); const [minutes, setMinutes] = useState(60);
    const blocked = !!status.data?.adapter_errors.length;
    const visibleAttention = useMemo(() => (attention.data?.items ?? []).filter(item => !item.snoozed), [attention.data]);
    if (status.isLoading) return <div className="grid gap-4 md:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-32" />)}</div>;
    if (status.isError || !status.data) return <Card><CardContent className="p-6 text-destructive">Operations Command Center is unavailable.</CardContent></Card>;
    return <div className="space-y-6">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
            <div><div className="flex items-center gap-2"><h1 className="text-3xl font-bold tracking-tight">Operations Command Center</h1><Badge variant={tone(status.data.headline)}>{status.data.headline}</Badge></div><p className="mt-1 text-muted-foreground">{status.data.summary}</p><p className="mt-1 text-xs text-muted-foreground">Snapshot {new Date(status.data.as_of).toLocaleString()}</p></div>
            <div className="flex flex-wrap items-center gap-2 rounded-md border p-2"><Input className="h-9 w-48" value={reason} onChange={event => setReason(event.target.value)} placeholder="Pause reason" /><Input className="h-9 w-24" type="number" min={1} max={1440} value={minutes} onChange={event => setMinutes(Number(event.target.value))} /><Button variant="destructive" disabled={!reason.trim() || blocked || pause.isPending} onClick={() => pause.mutate({ reason, minutes })}><Pause className="mr-2 h-4 w-4" />Pause fleet</Button></div>
        </div>
        {status.data.adapter_errors.length ? <Card className="border-destructive"><CardContent className="flex gap-2 p-4 text-sm text-destructive"><ShieldAlert className="h-4 w-4 shrink-0" />Commands are disabled until all pause-target adapters are readable: {status.data.adapter_errors.join(' · ')}</CardContent></Card> : null}
        <div className="grid gap-4 md:grid-cols-4"><Metric label="Needs attention" value={String(visibleAttention.length)} /><Metric label="Stalled lanes" value={String(status.data.fleet.filter(item => item.state === 'stalled').length)} /><Metric label="Paused lanes" value={String(status.data.fleet.filter(item => item.state === 'paused').length)} /><Metric label="Fleet lanes" value={String(status.data.fleet.length)} /></div>
        <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]">
            <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500" />Attention inbox</CardTitle><CardDescription>Each item stays owned by its domain cockpit.</CardDescription></CardHeader><CardContent className="space-y-3">{visibleAttention.slice(0, 16).map(item => <div key={item.key} className="flex flex-col gap-3 rounded-md border p-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap gap-2"><Badge variant={tone(item.severity)}>{item.severity}</Badge><Badge variant="outline">{item.system}</Badge><Badge variant="secondary">{item.kind}</Badge></div><Link className="mt-2 block font-medium hover:underline" href={item.href}>{item.title}</Link><p className="text-sm text-muted-foreground">{item.detail || 'No additional detail'} · {relative(item.first_seen)}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={ack.isPending} onClick={() => ack.mutate(item.key)}>Ack</Button><Button size="sm" variant="ghost" disabled={snooze.isPending} onClick={() => snooze.mutate({ key: item.key, minutes: 120 })}>Snooze 2h</Button></div></div>)}{!visibleAttention.length ? <p className="py-6 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 h-5 w-5 text-success" />No active fleet attention.</p> : null}</CardContent></Card>
            <Card><CardHeader><CardTitle className="flex items-center gap-2"><Clock3 className="h-5 w-5" />Since your last visit</CardTitle></CardHeader><CardContent className="space-y-3">{(briefing.data?.commands ?? []).slice(0, 8).map(command => <div key={command.id} className="rounded-md border p-3 text-sm"><div className="flex justify-between gap-2"><span className="font-medium">{command.command.replaceAll('_', ' ')}</span><Badge variant={tone(command.status)}>{command.status}</Badge></div><p className="mt-1 text-muted-foreground">{command.reason || command.scope}</p></div>)}{briefing.data?.commands.length ? <Button className="w-full" variant="outline" disabled={seen.isPending} onClick={() => seen.mutate(briefing.data!.through)}>Mark briefing read</Button> : <p className="text-sm text-muted-foreground">No new fleet commands since your last visit.</p>}</CardContent></Card>
        </div>
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><RefreshCw className="h-5 w-5" />Fleet status</CardTitle><CardDescription>Derived from each owner’s policy and run evidence. Unknown is intentionally not green.</CardDescription></CardHeader><CardContent className="space-y-2">{status.data.fleet.map(item => <div key={`${item.member_key}:${item.lane_key}:${item.tenant_id ?? 'platform'}`} className="flex flex-col gap-2 rounded-md border px-3 py-2 text-sm md:flex-row md:items-center"><div className="min-w-52"><Link href={item.cockpit_path} className="font-medium hover:underline">{item.member_label} · {item.lane_label}</Link><p className="text-xs text-muted-foreground">{item.tenant_id ?? 'platform'} · {item.kind}</p></div><Badge variant={tone(item.state)}>{item.state}</Badge><span className="text-muted-foreground">{item.mode || '—'}</span><span className="ml-auto text-xs text-muted-foreground">last run {relative(item.last_run_at)} · {item.liveness}</span>{item.pausable ? <Button size="sm" variant="outline" disabled={!reason.trim() || blocked || pauseMember.isPending} onClick={() => pauseMember.mutate({ member: item.member_key, lane: item.lane_key, reason, minutes })}><Pause className="mr-1 h-3 w-3" />Pause</Button> : null}</div>)}</CardContent></Card>
        <Card><CardHeader><CardTitle>Recent fleet commands</CardTitle></CardHeader><CardContent className="space-y-2">{(commands.data?.items ?? []).slice(0, 12).map(command => <div key={command.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border px-3 py-2 text-sm"><div><span className="font-medium">{command.command.replaceAll('_', ' ')}</span><span className="ml-2 text-muted-foreground">{command.scope} · {relative(command.created_at)}</span></div><div className="flex items-center gap-2"><Badge variant={tone(command.status)}>{command.status}</Badge>{command.command.startsWith('pause') ? <Button size="sm" variant="outline" disabled={resume.isPending} onClick={() => resume.mutate(command.id)}><Play className="mr-1 h-3 w-3" />Resume</Button> : null}</div></div>)}{!(commands.data?.items ?? []).length ? <p className="text-sm text-muted-foreground">No Command Center pauses have been issued.</p> : null}</CardContent></Card>
    </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <Card><CardHeader className="pb-2"><CardDescription>{label}</CardDescription><CardTitle>{value}</CardTitle></CardHeader></Card>; }
