import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {approveFeedRecoveryPlan,cancelFeedRecoveryRun,createFeedRecoveryPlan,executeFeedRecoveryRun,getFeedRecoveryPlan,issueFeedRecoveryReauth,listFeedRecoveryActions,listFeedRecoveryRuns,rollbackFeedRecoveryRun} from '@/lib/api/cms/feed-recovery';
import {toast} from '@/components/ui/toast';
export const feedRecoveryKeys={all:['feed-recovery'] as const,runs:()=>['feed-recovery','runs'] as const,actions:(id?:string)=>['feed-recovery','actions',id] as const,plan:(id?:string)=>['feed-recovery','plan',id] as const};
export function useFeedRecoveryRuns(){return useQuery({queryKey:feedRecoveryKeys.runs(),queryFn:listFeedRecoveryRuns,staleTime:10_000,refetchInterval:20_000});}
export function useFeedRecoveryActions(id?:string){return useQuery({queryKey:feedRecoveryKeys.actions(id),queryFn:()=>listFeedRecoveryActions(id!),enabled:Boolean(id),staleTime:10_000,refetchInterval:20_000});}
export function useFeedRecoveryPlan(id?:string){return useQuery({queryKey:feedRecoveryKeys.plan(id),queryFn:()=>getFeedRecoveryPlan(id!),enabled:Boolean(id)});}
export function useCreateFeedRecoveryPlan(){const qc=useQueryClient();return useMutation({mutationFn:createFeedRecoveryPlan,onSuccess:()=>{qc.invalidateQueries({queryKey:feedRecoveryKeys.all});toast({title:'Recovery preflight prepared',description:'The manifest is immutable until it expires or is refreshed.',variant:'success'});},onError:(e:Error)=>toast({title:'Recovery preflight failed',description:e.message,variant:'destructive'})});}
export function useApproveFeedRecoveryPlan(){const qc=useQueryClient();return useMutation({mutationFn:({plan,phrase}:{plan:Awaited<ReturnType<typeof getFeedRecoveryPlan>>;phrase:string})=>approveFeedRecoveryPlan(plan.id,phrase),onSuccess:()=>{qc.invalidateQueries({queryKey:feedRecoveryKeys.all});toast({title:'Recovery approval recorded',description:'A 60-second persisted cancellation window is now active.',variant:'success'});},onError:(e:Error)=>toast({title:'Recovery approval failed',description:e.message,variant:'destructive'})});}
function useRunMutation(fn:(id:string)=>Promise<unknown>,title:string){const qc=useQueryClient();return useMutation({mutationFn:fn,onSuccess:()=>{qc.invalidateQueries({queryKey:feedRecoveryKeys.all});toast({title,variant:'success'});},onError:(e:Error)=>toast({title:`${title} failed`,description:e.message,variant:'destructive'})});}
export function useExecuteFeedRecoveryRun(){const qc=useQueryClient();return useMutation({mutationFn:async ({id,planID,password}:{id:string;planID:string;password:string})=>{const plan=await getFeedRecoveryPlan(planID);const proof=await issueFeedRecoveryReauth(password,plan);return executeFeedRecoveryRun(id,proof.proof);},onSuccess:()=>{qc.invalidateQueries({queryKey:feedRecoveryKeys.all});toast({title:'Recovery phase advanced',variant:'success'});},onError:(e:Error)=>toast({title:'Recovery phase advanced failed',description:e.message,variant:'destructive'})});}
export function useCancelFeedRecoveryRun(){return useRunMutation(cancelFeedRecoveryRun,'Recovery run cancelled');}
export function useRollbackFeedRecoveryRun(){return useRunMutation(rollbackFeedRecoveryRun,'Recovery rollback completed');}
