'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {useApproveFeedRecoveryPlan,useCancelFeedRecoveryRun,useCreateFeedRecoveryPlan,useExecuteFeedRecoveryRun,useFeedRecoveryActions,useFeedRecoveryPlan,useFeedRecoveryRuns,useRollbackFeedRecoveryRun} from '@/hooks/use-feed-recovery';
import type {FeedRecoveryLane,FeedRecoveryLevel} from '@/types/platform/feed-recovery';

const resumablePhases=['cancel_window','verification_wait','partial','failed','executing','reseeding','purging_news','reseeding_news','purging_media','reseeding_media'];

export default function FeedRecoveryPage(){
 const [lane,setLane]=useState<FeedRecoveryLane>('news');
 const [level,setLevel]=useState<FeedRecoveryLevel>('repair');
 const [noFullRollback,setNoFullRollback]=useState(false);
 const [planID,setPlanID]=useState('');
 const [selectedRunID,setSelectedRunID]=useState<string>();
 const [password,setPassword]=useState('');
 const [phrase,setPhrase]=useState('');
 const create=useCreateFeedRecoveryPlan(); const plan=useFeedRecoveryPlan(planID); const approve=useApproveFeedRecoveryPlan(); const execute=useExecuteFeedRecoveryRun(); const cancel=useCancelFeedRecoveryRun(); const rollback=useRollbackFeedRecoveryRun(); const runs=useFeedRecoveryRuns(); const actions=useFeedRecoveryActions(selectedRunID); const current=plan.data;
 const expectedPhrase=current?.level==='purge_reseed'?`PURGE ${current.lane.toUpperCase()} ${current.target_count} ITEMS ${current.manifest_hash.slice(0,12).toUpperCase()}${current.no_full_rollback?' NO FULL ROLLBACK':''}`:`APPROVE FEED RECOVERY ${current?.manifest_hash.slice(0,12).toUpperCase()||''}`;
 return <main className="space-y-6 p-4 md:p-8">
  <div><h1 className="text-2xl font-semibold">Feed Recovery</h1><p className="text-sm text-muted-foreground">Repair and Rotate are derived-state workflows. Low-Space Purge &amp; Reseed is admin-only, manifest-bound, checkpoint-preserving, and may show an expected-empty feed while reseeding.</p></div>
  <Card><CardHeader><CardTitle>Preflight</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2">{(['news','media','both'] as FeedRecoveryLane[]).map(x=><Button key={x} variant={lane===x?'default':'outline'} onClick={()=>setLane(x)}>{x}</Button>)}{(['repair','rotate','purge_reseed'] as FeedRecoveryLevel[]).map(x=><Button key={x} variant={level===x?'secondary':'outline'} onClick={()=>setLevel(x)}>{x.replace('_',' ')}</Button>)}</div>{level==='purge_reseed'&&<label className="flex items-center gap-2 text-sm"><Checkbox checked={noFullRollback} onCheckedChange={v=>setNoFullRollback(v===true)}/> I acknowledge that full rollback may be unavailable</label>}<p className="text-xs text-muted-foreground">Purge &amp; Reseed deletes only the frozen content manifest. Sources, schedules, credentials, and checkpoints are preserved. Both lanes execute sequentially.</p><Button disabled={create.isPending} onClick={async()=>{const p=await create.mutateAsync({lane,level,capacity_mode:level==='purge_reseed'?'low_space_reset':'safe_cutover',no_full_rollback:level==='purge_reseed'?noFullRollback:false});setPlanID(p.id)}}>Prepare recovery plan</Button></CardContent></Card>
  {current&&<Card><CardHeader><CardTitle>Plan <Badge>{current.state}</Badge> <Badge variant="outline">{current.capacity_mode.replace('_',' ')}</Badge></CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Sources: {current.source_count} · exact frozen targets: {current.target_count} · proof {current.source_checksum.slice(0,12)}…</p><p>Manifest: {current.manifest_hash}</p>{current.level==='purge_reseed'&&<p>Reset semantics: <Badge variant="outline">complete lane reset</Badge> · all eligible unprotected content · target root {current.target_root_hash?.slice(0,12)||'—'}… · {current.target_segments ?? 0} immutable segments</p>}<p className="text-xs text-muted-foreground">The target count is the complete approved deletion scope; reseed remains separately capped at the configured lookback limits. Sources, schedules, credentials, and checkpoints are preserved. Full rollback: {current.no_full_rollback?'not guaranteed':'available where the owner provides a recovery map'}.</p><p>Confirmation: <code>{expectedPhrase}</code></p><Input type="password" placeholder="Admin password for fresh re-auth" value={password} onChange={e=>setPassword(e.target.value)}/><Input placeholder="Confirmation phrase" value={phrase} onChange={e=>setPhrase(e.target.value)}/><Button disabled={approve.isPending||!password||!phrase} onClick={()=>approve.mutate({plan:current,password,phrase})}>Approve</Button></CardContent></Card>}
  <Card><CardHeader><CardTitle>Recovery ledger</CardTitle></CardHeader><CardContent>{runs.data?.data?.length?<ul className="space-y-2">{runs.data.data.map(run=><li key={run.id} className="rounded-md border p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{run.phase}</Badge><Badge variant="outline">{run.lane}</Badge>{run.expected_empty&&<Badge variant="warning">expected empty</Badge>}<span className="text-xs text-muted-foreground">{new Date(run.created_at).toLocaleString()}</span>{run.verification_due_at&&<span className="text-xs text-muted-foreground">probe 2 due {new Date(run.verification_due_at).toLocaleString()}</span>}{run.rollback_deadline&&<span className="text-xs text-muted-foreground">rollback until {new Date(run.rollback_deadline).toLocaleString()}</span>}{run.error&&<span className="text-xs text-destructive">{run.error}</span>}<Button size="sm" variant="outline" onClick={()=>setSelectedRunID(run.id)}>Inspect gates</Button>{resumablePhases.includes(run.phase)&&<Button size="sm" onClick={()=>execute.mutate(run.id)} disabled={execute.isPending}>Continue</Button>}{run.phase==='cancel_window'&&<Button size="sm" variant="outline" onClick={()=>cancel.mutate(run.id)} disabled={cancel.isPending}>Cancel</Button>}{run.outcome==='succeeded'&&run.rollback_deadline&&new Date(run.rollback_deadline)>new Date()&&<Button size="sm" variant="outline" onClick={()=>rollback.mutate(run.id)} disabled={rollback.isPending}>Rollback</Button>}</div><p className="mt-2 text-xs text-muted-foreground">Lease {run.lane_lease||'not acquired'} · correlation {run.correlation_id}</p></li>)}</ul>:<p className="text-sm text-muted-foreground">No recovery runs recorded.</p>}</CardContent></Card>
  {selectedRunID&&<Card><CardHeader><CardTitle>D27 gate and saga evidence</CardTitle></CardHeader><CardContent className="space-y-2">{actions.data?.length?actions.data.map(action=><div key={action.id} className="rounded-md border p-3 text-xs"><div className="flex items-center gap-2"><Badge variant={action.state==='succeeded'?'success':action.state==='blocked'?'destructive':'secondary'}>{action.state}</Badge><span className="font-medium">{action.action_type}</span><span className="text-muted-foreground">{new Date(action.created_at).toLocaleString()}</span></div>{action.error&&<p className="mt-1 text-destructive">{action.error}</p>}<pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap text-[11px] text-muted-foreground">{JSON.stringify(action.evidence??{},null,2)}</pre></div>):<p className="text-sm text-muted-foreground">No action evidence recorded for this run.</p>}</CardContent></Card>}
 </main>
}
